### PR TITLE
Fix spelling errors in README

### PR DESCRIPTION
**Pull request by gabrielreid**

### CODE REVIEW

**Review by cupcicm — APPROVED** [review]

**Comment by cupcicm** [comment]
Those branch names make me think you aren't using `opp` yet 😅

**Comment by gabrielreid** [comment]
> Those branch names make me think you aren't using opp yet 😅
Funny fact: I tried to use opp, but I can't (or at least not easily), because I'm working on a fork but my upstream is this repo.

I'll add a new issue for this :-)

**Comment by gabrielreid** [comment]
Also: I can't merge PRs on this repo, so if we want this to go in then I think you'll need to merge it @cupcicm

**Comment by cupcicm** [comment]
Ah yes, opp doesn't work on forks. I added you as a collaborator, you can
use the repo directly.

Manu

**Pull request merged**
